// Nuxt's recommended rules (Vue, TypeScript, imports), generated by @nuxt/eslint during `nuxt prepare`.
import withNuxt from './.nuxt/eslint.config.mjs'

export default withNuxt({
  ignores: ['reports/**', 'test-results/**', '.output/**', '.wrangler/**'],
})
